version: "3.3"
services:
  db:
    container_name: recipes-example-db
    restart: always
    image: recipes-example-db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 5432:5432
  graphql:
    container_name: recipes-example-graphql
    restart: always
    image: recipes-example-graphql
    build:
        context: ./graphql
    env_file:
        - ./.env
    depends_on:
        - db
    networks:
        - network
    ports:
        - 5433:5433
  

networks:
  network:

volumes:
  db: